import { Messages } from "../types";


export const successMessages: Messages = {
  200: {
    en: 'OK',
    es: 'OK',
    fr: 'OK',
    de: 'OK',
    ja: 'OK',
    zh: '好的',
  },
  201: {
    en: 'Created',
    es: 'Creado',
    fr: 'Créé',
    de: 'Erstellt',
    ja: '作成された',
    zh: '已创建',
  },
  202: {
    en: 'Accepted',
    es: 'Aceptado',
    fr: 'Accepté',
    de: 'Akzeptiert',
    ja: '受け入れられました',
    zh: '已接受',
  },
  203: {
    en: 'Non-Authoritative Information',
    es: 'Información no autoritativa',
    fr: 'Information non autorisée',
    de: 'Nicht autoritative Information',
    ja: '信頼できない情報',
    zh: '非官方信息',
  },
  204: {
    en: 'No Content',
    es: 'Sin contenido',
    fr: 'Pas de contenu',
    de: 'Kein Inhalt',
    ja: 'コンテンツなし',
    zh: '无内容',
  },
  205: {
    en: 'Reset Content',
    es: 'Restablecer contenido',
    fr: 'Contenu réinitialisé',
    de: 'Inhalt zurücksetzen',
    ja: 'コンテンツをリセット',
    zh: '重置内容',
  },
  206: {
    en: 'Partial Content',
    es: 'Contenido parcial',
    fr: 'Contenu partiel',
    de: 'Teilinhalt',
    ja: '部分的なコンテンツ',
    zh: '部分内容',
  },
  207: {
    en: 'Multi-Status',
    es: 'Multiestado',
    fr: 'Multi-Statut',
    de: 'Mehrere Status',
    ja: '複数のステータス',
    zh: '多状态',
  },
  208: {
    en: 'Already Reported',
    es: 'Ya reportado',
    fr: 'Déjà signalé',
    de: 'Bereits gemeldet',
    ja: 'すでに報告済み',
    zh: '已经报告',
  },
  226: {
    en: 'IM Used',
    es: 'IM utilizado',
    fr: 'IM utilisé',
    de: 'IM verwendet',
    ja: 'IMが使用されました',
    zh: '已使用IM',
  },
  300: {
    en: 'Multiple Choices',
    es: 'Elecciones múltiples',
    fr: 'Choix multiples',
    de: 'Mehrere Auswahlmöglichkeiten',
    ja: '複数の選択肢',
    zh: '多种选择',
  },
  301: {
    en: 'Moved Permanently',
    es: 'Movido permanentemente',
    fr: 'Déplacé de façon permanente',
    de: 'Dauerhaft verschoben',
    ja: '恒久的に移動しました',
    zh: '永久移动',
  },
  302: {
    en: 'Found',
    es: 'Encontrado',
    fr: 'Trouvé',
    de: 'Gefunden',
    ja: '見つかりました',
    zh: '已找到',
  },
  303: {
    en: 'See Other',
    es: 'Ver otro',
    fr: 'Voir un autre',
    de: 'Siehe andere',
    ja: '他を参照',
    zh: '查看其他',
  },
  304: {
    en: 'Not Modified',
    es: 'No modificado',
    fr: 'Non modifié',
    de: 'Nicht verändert',
    ja: '変更されていません',
    zh: '未修改',
  },
  305: {
    en: 'Use Proxy',
    es: 'Usar proxy',
    fr: 'Utiliser un proxy',
    de: 'Proxy verwenden',
    ja: 'プロキシを使用',
    zh: '使用代理',
  },
  307: {
    en: 'Temporary Redirect',
    es: 'Redirección temporal',
    fr: 'Redirection temporaire',
    de: 'Temporäre Weiterleitung',
    ja: '一時的なリダイレクト',
    zh: '临时重定向',
  },
  308: {
    en: 'Permanent Redirect',
    es: 'Redirección permanente',
    fr: 'Redirection permanente',
    de: 'Permanente Weiterleitung',
    ja: '永久リダイレクト',
    zh: '永久重定向',
  },
};